basePath: /
definitions:
  posts.createPostInput:
    properties:
      body:
        type: string
    required:
    - body
    type: object
  posts.createPostOutput:
    properties:
      id:
        type: integer
    type: object
  posts.getPostOutput:
    properties:
      attachmentIds:
        items:
          type: integer
        type: array
      author:
        type: string
      body:
        type: string
      created:
        type: string
      id:
        type: integer
      isUpdated:
        type: boolean
      likeCount:
        type: integer
    type: object
  posts.updatePostInput:
    properties:
      body:
        type: string
    required:
    - body
    type: object
  users.loginInput:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  users.loginOutput:
    properties:
      token:
        type: string
    type: object
  users.registerInput:
    properties:
      email:
        type: string
      password:
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  users.userOutput:
    properties:
      created:
        type: string
      email:
        type: string
      updated:
        type: string
      userId:
        type: integer
    type: object
  utils.ErrorOutput:
    properties:
      errors:
        items:
          $ref: '#/definitions/utils.ErrorResponse'
        type: array
      message:
        type: string
    type: object
  utils.ErrorResponse:
    properties:
      field:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: This is a instagram-like server (instalike).
  termsOfService: http://swagger.io/terms/
  title: InstaLike API
  version: "1.0"
paths:
  /api/posts:
    get:
      description: gets all posts
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/posts.getPostOutput'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      security:
      - Bearer: []
      summary: Gets all posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: creates a new post
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: The input post struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/posts.createPostInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/posts.createPostOutput'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
      security:
      - Bearer: []
      summary: Create post
      tags:
      - posts
  /api/posts/{postId}:
    delete:
      description: deletes post by post id. only author of the post is allowed to
        delete the post
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: postId
        required: true
        type: integer
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      security:
      - Bearer: []
      summary: Deletes post
      tags:
      - posts
    get:
      description: gets a post by post id
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: postId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/posts.getPostOutput'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      security:
      - Bearer: []
      summary: Gets a post by post id
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: updates post. only author of the post is allowed to update the
        post
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: postId
        required: true
        type: integer
      - description: The update post struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/posts.updatePostInput'
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      security:
      - Bearer: []
      summary: Updates post
      tags:
      - posts
  /api/posts/{postId}/attachment:
    post:
      consumes:
      - multipart/form-data
      description: attaches multimedia file to post. only author of the post is allowed
        to add files to the post. only images and videos are allowed to be uploaded
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Post ID
        in: path
        name: postId
        required: true
        type: integer
      - description: The file upload form
        in: formData
        name: file
        required: true
        type: file
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "413":
          description: Request Entity Too Large
        "422":
          description: Unprocessable Entity
      security:
      - Bearer: []
      summary: Attaches multimedia file to post
      tags:
      - posts
  /api/users/login:
    post:
      consumes:
      - application/json
      description: performs user login, returns jwt token and sets http-only cookie.
      parameters:
      - description: The input login struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.loginInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.loginOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorOutput'
        "401":
          description: Unauthorized
      summary: User login
      tags:
      - auth
  /api/users/me:
    get:
      description: gets currenly logger in user information
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.userOutput'
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      security:
      - Bearer: []
      summary: Current user information
      tags:
      - auth
  /api/users/register:
    post:
      consumes:
      - application/json
      description: registers user.
      parameters:
      - description: The input register struct
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/users.registerInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.ErrorOutput'
        "409":
          description: Conflict
      summary: User register
      tags:
      - auth
  /media/attachments/{attachmentId}:
    get:
      description: downloads multimedia file by post's attachmentId
      parameters:
      - description: Authorization
        in: header
        name: Authorization
        required: true
        type: string
      - description: Attachment ID
        in: path
        name: attachmentId
        required: true
        type: integer
      produces:
      - '*/*'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
      security:
      - Bearer: []
      summary: Downloads multimedia file by post's attachmentId
      tags:
      - media
schemes:
- http
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
