basePath: /
host: localhost:3000
info:
  contact: {}
  description: This is a instagram-like server (instalike).
  termsOfService: http://swagger.io/terms/
  title: InstaLike API
  version: "1.0"
paths: {}
schemes:
- http
securityDefinitions:
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
